name: flutter_tutorial_overlay

description: "A Flutter package to create interactive tutorials, onboarding flows, guided tours, and user instruction overlays with step-by-step highlights and tooltips."

version: 1.0.4
homepage: https://github.com/AliA5y/flutter_tutorial_overlay
repository: https://github.com/AliA5y/flutter_tutorial_overlay
issue_tracker: https://github.com/AliA5y/flutter_tutorial_overlay/issues

environment:
  sdk: ^3.8.1
  flutter: ">=3.0.0"

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^5.0.0
  test: ^1.24.0
# scripts:
#   test: flutter test
#   test:coverage: flutter test --coverage
